# Generated by Django 4.1.1 on 2022-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.BigIntegerField(null=True),
        ),
    ]
