# Generated by Django 4.1.1 on 2022-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, 'female'), (2, 'male')], null=True),
        ),
    ]
