# Generated by Django 4.1.1 on 2022-09-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_qualification_datetimejob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimejob',
            old_name='Time_from',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='datetimejob',
            old_name='Time_to',
            new_name='time_to',
        ),
    ]
