# Generated by Django 4.1.1 on 2022-09-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_time_from_datetimejob_time_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('visit_time', models.SmallIntegerField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'not approved'), (2, 'approved')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DateTimeJob',
        ),
    ]
