# Generated by Django 4.1.1 on 2022-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_datetimework_delete_datetimejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimework',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'not approved'), (2, 'approved')], default=1),
        ),
    ]
