# Generated by Django 4.1.1 on 2022-09-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_datetimework_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='specialization',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='qualification',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.service'),
            preserve_default=False,
        ),
    ]
