# Generated by Django 4.1.1 on 2022-09-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_service_rename_specialization_qualification_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.service'),
        ),
    ]
