# Generated by Django 4.1.1 on 2022-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_datetimework_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimework',
            name='visit_time',
            field=models.TimeField(),
        ),
    ]
