# Generated by Django 4.1.1 on 2022-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_datetimework_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimework',
            name='visit_time',
            field=models.SmallIntegerField(),
        ),
    ]
