# Generated by Django 4.1.1 on 2022-10-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_datetimework_doctor_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.TimeField()),
                ('date_time_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_time_work', to='website.datetimework')),
            ],
        ),
    ]
