# Generated by Django 4.1.1 on 2022-10-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_timework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeWork',
            new_name='TimeAppointment',
        ),
    ]
