# Generated by Django 4.1.1 on 2022-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_timework_timeappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='room',
            field=models.SmallIntegerField(null=True),
        ),
    ]
