# Generated by Django 4.1.1 on 2022-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'not approved'), (2, 'approved')], default=1),
        ),
    ]
