# Generated by Django 4.1.1 on 2022-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_opinion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
