# Generated by Django 4.1.1 on 2022-10-02 22:47

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_appointment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_img', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'not approved'), (2, 'approved')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
