# Generated by Django 4.1.1 on 2022-10-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.TextField(null=True)),
                ('diagnosis', models.CharField(max_length=2048, null=True)),
                ('recommendations', models.CharField(max_length=2048, null=True)),
                ('medications', models.CharField(max_length=2048, null=True)),
                ('remarks', models.TextField(null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='website.appointment')),
            ],
        ),
        migrations.AlterField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
