# Generated by Django 4.1.1 on 2022-10-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_appointment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='website.appointment'),
        ),
    ]
