# Generated by Django 4.1.1 on 2022-10-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_appointmentnotes_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='website.appointment'),
        ),
    ]
