# Generated by Django 4.1.1 on 2022-10-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_appointmentnotes_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentnotes',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appointment', serialize=False, to='website.appointment'),
        ),
    ]
