# Generated by Django 4.1.1 on 2022-10-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_remove_appointmentnotes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotes',
            name='id',
            field=models.BigAutoField(default=None, auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='website.appointment'),
        ),
    ]
