# Generated by Django 4.1.1 on 2022-10-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_appointmentnotes_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentnotes',
            old_name='appointment',
            new_name='appointment_id',
        ),
    ]
