# Generated by Django 4.1.1 on 2022-10-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_appointment_appointmentnotes_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentnotes',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appointment', serialize=False, to='website.appointment'),
        ),
    ]
