# Generated by Django 4.1.1 on 2022-10-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_appointmentnotes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentnotes',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
