# Generated by Django 4.1.1 on 2022-10-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_rename_appointment_appointmentnotes_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentnotes',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
