# Generated by Django 4.1.1 on 2022-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_rename_appointment_id_appointmentnotes_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='created',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='AppointmentNotes',
        ),
    ]
