# Generated by Django 4.1.1 on 2022-10-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_opinion_created_alter_appointment_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotes',
            fields=[
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.appointment')),
                ('interview', models.TextField(null=True)),
                ('diagnosis', models.CharField(max_length=2048, null=True)),
                ('recommendations', models.CharField(max_length=2048, null=True)),
                ('remarks', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
