# Generated by Django 4.1.1 on 2022-10-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_appointmentnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotes',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.appointment', unique=True),
        ),
    ]
