# Generated by Django 4.1.1 on 2022-10-05 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_service_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
