# Generated by Django 4.1.1 on 2022-10-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_alter_appointmentnotes_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('client_permission', 'Hospital patient'), ('doctor_permission', 'Hospital worker'), ('administrator_permission', 'Website management'))},
        ),
    ]
